grafana:
  enabled: true
  adminPassword: enginebench-change-me
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
prometheus-node-exporter:
  enabled: true
