#!/usr/bin/env bash

DASHBOARD_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CONFIG_FILE=${DASHBOARD_CONFIG:-"$DASHBOARD_DIR/.env.local"}

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Missing $CONFIG_FILE. Copy $DASHBOARD_DIR/.env.example to $CONFIG_FILE and edit it." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$CONFIG_FILE"
set +a

: "${RUNPOD_HOST:?Set RUNPOD_HOST in $CONFIG_FILE}"
: "${RUNPOD_PORT:?Set RUNPOD_PORT in $CONFIG_FILE}"
: "${RUNPOD_USER:?Set RUNPOD_USER in $CONFIG_FILE}"
: "${RUNPOD_SSH_KEY:?Set RUNPOD_SSH_KEY in $CONFIG_FILE}"

LOCAL_API_PORT=${LOCAL_API_PORT:-8787}
REMOTE_API_HOST=${REMOTE_API_HOST:-127.0.0.1}
REMOTE_API_PORT=${REMOTE_API_PORT:-8787}
REMOTE_WORKSPACE=${REMOTE_WORKSPACE:-/workspace}
REMOTE_APP_DIR=${REMOTE_APP_DIR:-$REMOTE_WORKSPACE/benchmark-dashboard}
REMOTE_SWEEP_SCRIPT=${REMOTE_SWEEP_SCRIPT:-$REMOTE_WORKSPACE/concurrency_sweep.py}
REMOTE_PYTHON=${REMOTE_PYTHON:-/opt/vllm-venv/bin/python}
REMOTE_VLLM_BIN=${REMOTE_VLLM_BIN:-/opt/vllm-venv/bin/vllm}
REMOTE_PYTHON_VERSION=${REMOTE_PYTHON_VERSION:-3.11}
VLLM_VERSION=${VLLM_VERSION:-0.10.2}
REMOTE_HF_HOME=${REMOTE_HF_HOME:-$REMOTE_WORKSPACE/huggingface}
REMOTE_RUN_ROOT=${REMOTE_RUN_ROOT:-$REMOTE_WORKSPACE/past_runs}
REMOTE_OUTPUT=${REMOTE_OUTPUT:-$REMOTE_WORKSPACE/output.txt}
BENCHMARK_MODEL=${BENCHMARK_MODEL:-Qwen/Qwen2.5-7B-Instruct}
BENCHMARK_CONCURRENCY=${BENCHMARK_CONCURRENCY:-"1 8 16 32 64 128 256 512"}
BENCHMARK_MAX_NUM_SEQS=${BENCHMARK_MAX_NUM_SEQS:-256}
BENCHMARK_MAX_NUM_BATCHED_TOKENS=${BENCHMARK_MAX_NUM_BATCHED_TOKENS:-8192}
BENCHMARK_MAX_MODEL_LEN=${BENCHMARK_MAX_MODEL_LEN:-32768}
BENCHMARK_GPU_MEMORY_UTILIZATION=${BENCHMARK_GPU_MEMORY_UTILIZATION:-0.9}
BENCHMARK_INPUT_TOKENS=${BENCHMARK_INPUT_TOKENS:-1024}
BENCHMARK_OUTPUT_TOKENS=${BENCHMARK_OUTPUT_TOKENS:-256}
