apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enginebench-ray
resources: [namespace.yaml, deployment.yaml, service.yaml]
configMapGenerator:
  - name: ray-app
    files: [enginebench_ray.py]
